version: '3.9'

services:
  web:
    build: .
    command: bash -c "chmod +x migration-init.sh && ./migration-init.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: graph_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A your_project_name worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
